Spg.TestAdministrator/Spg.TestAdministrator/src/Spg.TestAdministrator.WebApp/Controllers/ExamController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Spg.TestAdministrator.Business.Application;
using Spg.TestAdministrator.Business.Domain.Exceptions;
using Spg.TestAdministrator.Business.Domain.Interfaces;
using Spg.TestAdministrator.Business.Domain.Models;
using Spg.TestAdministrator.WebApp.Dtos;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Linq.Expressions;
using System.Threading;
using System.Threading.Tasks;

namespace Spg.TestAdministrator.WebApp.Controllers
{
    public class ExamController : Controller
    {
        private readonly IExamService<Test> _examService;
        private readonly IReadOnlyExamService<Test> _readOnlyExamService;
        private readonly IReadOnlyTeacherService<Teacher> _readOnlyTeacherService;
        private readonly IReadOnlySchoolClassService<Schoolclass> _readOnlySchoolClassService;
        private readonly IReadOnlyLessonService<Lesson> _readOnlyLessonService;

        public ExamController(
            IReadOnlyExamService<Test> readOnlyExamService, 
            IExamService<Test> examService,
            IReadOnlyTeacherService<Teacher> readOnlyTeacherService,
            IReadOnlySchoolClassService<Schoolclass> readOnlySchoolClassService,
            IReadOnlyLessonService<Lesson> readOnlyLessonService)
        {
            _examService = examService;
            _readOnlyExamService = readOnlyExamService;
            _readOnlyTeacherService = readOnlyTeacherService;
            _readOnlySchoolClassService = readOnlySchoolClassService;
            _readOnlyLessonService = readOnlyLessonService;
        }

        public async Task<IActionResult> AjaxIndex()
        {
            IQueryable<Test> result = _examService
                .Table(null, null)
                .Include(t => t.TE_TeacherNavigation);

            PagenatedList<Test> model = await PagenatedList<Test>.CreateAsync(result, 1, 10);

            return View(model);
        }

        public async Task<IActionResult> IndexPartial(string filter, string sortOrder, int pageIndex = 1)
        {
            ViewData["CurrentSort"] = sortOrder;

            ViewData["IdSortParm"] = String.IsNullOrEmpty(sortOrder) ? "id_desc" : "";
            ViewData["DateSortParm"] = sortOrder == "date" ? "date_desc" : "date";
            ViewData["SubjectSortParm"] = sortOrder == "subject" ? "subject_desc" : "subject";

            Expression<Func<Test, bool>> filterExpression = null;
            if (!string.IsNullOrEmpty(filter))
            {
                filterExpression = t => t.TE_Teacher.Contains(filter)
                    || t.TE_TeacherNavigation.T_Lastname.Contains(filter);
            }

            Func<IQueryable<Test>, IOrderedQueryable<Test>> sortOrderExpression = null;
            if (!string.IsNullOrEmpty(sortOrder))
            {
                switch (sortOrder)
                {
                    case "date":
                        sortOrderExpression = l => l.OrderBy(s => s.TE_Date);
                        break;
                    case "date_desc":
                        sortOrderExpression = l => l.OrderByDescending(s => s.TE_Date);
                        break;
                    case "subject":
                        sortOrderExpression = l => l.OrderBy(s => s.TE_Subject);
                        break;
                    case "subject_desc":
                        sortOrderExpression = l => l.OrderByDescending(s => s.TE_Subject);
                        break;
                    case "id_desc":
                        sortOrderExpression = l => l.OrderByDescending(s => s.TE_ID);
                        break;
                    default:
                        sortOrderExpression = l => l.OrderBy(s => s.TE_ID);
                        break;
                }
            }

            IQueryable<Test> result = _examService
                .Table(filterExpression, sortOrderExpression)
                .Include(t => t.TE_TeacherNavigation);

            PagenatedList<Test> model = await PagenatedList<Test>.CreateAsync(result, pageIndex, 10);

            return PartialView("_ExamList", model);
        }

        public IActionResult VueIndex()
        {
            return View();
        }

        public async Task<IActionResult> VueTableContent(string filter, string sortField, int pageIndex = 1)
        {
            Expression<Func<Test, bool>> filterExpression = null;
            if (!string.IsNullOrEmpty(filter))
            {
                filterExpression = t => t.TE_Teacher.Contains(filter)
                    || t.TE_TeacherNavigation.T_Lastname.Contains(filter);
            }

            Func<IQueryable<Test>, IOrderedQueryable<Test>> sortOrderExpression = null;
            if (!string.IsNullOrEmpty(sortField))
            {
                sortOrderExpression = sortField switch
                {
                    "date" => l => l.OrderBy(s => s.TE_Date),
                    "date_desc" => l => l.OrderByDescending(s => s.TE_Date),
                    "subject" => l => l.OrderBy(s => s.TE_Subject),
                    "subject_desc" => l => l.OrderByDescending(s => s.TE_Subject),
                    "id_desc" => l => l.OrderByDescending(s => s.TE_ID),
                    _ => l => l.OrderBy(s => s.TE_ID),
                };
            }

            IQueryable<Test> result = _examService
                .Table(filterExpression, sortOrderExpression)
                .Include(t => t.TE_TeacherNavigation);

            PagenatedList<Test> model = await PagenatedList<Test>.CreateAsync(result, pageIndex, 10);

            return Ok(new ExamListDto()
            {
                Exams = model.Select(t => new TestDto()
                {
                    TE_ID = t.TE_ID,
                    TE_Date = t.TE_Date,
                    TE_Subject = t.TE_Subject,
                    TE_TeacherNavigation = TeacherDto.Map(t.TE_TeacherNavigation)
                })
                .ToList(),
                TotalPages = model.TotalPages
            });
        }


        [HttpGet()]
        public async Task<IActionResult> Index(string filter, string currentFilter, string sortOrder, int pageIndex = 1)
        {
            ViewData["CurrentFilter"] = currentFilter;
            ViewData["CurrentSort"] = sortOrder;

            ViewData["IdSortParm"] = String.IsNullOrEmpty(sortOrder) ? "id_desc" : "";
            ViewData["DateSortParm"] = sortOrder == "date" ? "date_desc" : "date";
            ViewData["SubjectSortParm"] = sortOrder == "subject" ? "subject_desc" : "subject";

            filter = filter ?? currentFilter;

            Expression<Func<Test, bool>> filterExpression = null;
            if (!string.IsNullOrEmpty(filter))
            {
                filterExpression = t => t.TE_Teacher.Contains(filter)
                    || t.TE_TeacherNavigation.T_Lastname.Contains(filter);

                ViewData["CurrentFilter"] = filter;
            }

            Func<IQueryable<Test>, IOrderedQueryable<Test>> sortOrderExpression = null;
            if (!string.IsNullOrEmpty(sortOrder))
            {
                switch (sortOrder)
                {
                    case "date":
                        sortOrderExpression = l => l.OrderBy(s => s.TE_Date);
                        break;
                    case "date_desc":
                        sortOrderExpression = l => l.OrderByDescending(s => s.TE_Date);
                        break;
                    case "subject":
                        sortOrderExpression = l => l.OrderBy(s => s.TE_Subject);
                        break;
                    case "subject_desc":
                        sortOrderExpression = l => l.OrderByDescending(s => s.TE_Subject);
                        break;
                    case "id_desc":
                        sortOrderExpression = l => l.OrderByDescending(s => s.TE_ID);
                        break;
                    default:
                        sortOrderExpression = l => l.OrderBy(s => s.TE_ID);
                        break;
                }
            }

            IQueryable<Test> result = _readOnlyExamService
                .Table(filterExpression, sortOrderExpression)
                .Include(t => t.TE_TeacherNavigation);

            PagenatedList<Test> model = await PagenatedList<Test>.CreateAsync(result, pageIndex, 10);

            return View(model);
        }

        [HttpGet()]
        [Authorize(Policy = "PolicyForTeachers")]
        public async Task<IActionResult> Edit(Guid id)
        {
            // TODO: Woher die Daten nehmen, View aufrufen
            Test model = _examService.GetById(id);
            if (model == null)
            {
                return NotFound();
            }

            //TODO: Für die Class und für die Lesson die Drop-Down-Boxes befüllen
            ViewData["TE_Teacher"] = new SelectList(_readOnlyTeacherService.Table(null, null), nameof(Teacher.T_ID), nameof(Teacher.FullName));
            ViewData["TE_Class"] = new SelectList(_readOnlySchoolClassService.Table(null, null), "C_ID", "C_ID");
            ViewData["TE_Lesson"] = new SelectList(await _readOnlyLessonService.ListByTeacher().ToListAsync(), "L_ID", "LessonDescription");

            return View(model);
        }

        [HttpPost()]
        [Authorize(Policy = "PolicyForTeachers")]
        public async Task<IActionResult> Edit(Guid id, Test model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }
            try
            {
                await _examService.UpdateAsync(id, model);
            }
            catch (UpdateException ex)
            {
                ModelState.AddModelError("", ex.Message);
                TempData["Error"] = $"{ex.Message} (aus TempData)";

Spg.TestAdministrator/Spg.TestAdministrator/src/Spg.TestAdministrator.WebApp/Views/Exam/AjaxIndex.cshtml
@model PagenatedList<Test>

<h3>Liste aller Test (Lösung mit AJAX)</h3>

<p>
    Diese Seite wird jetzt nur einmal geladen, wenn die URl: /Exam/Index aufgerufen wird
    Die Tabelle + Buttons sind in einer partial View ausgelagert. Diese wird hier beim Laden
    der Seite mitgeladen, dann aber (bei den klicks aus einen der Buttons/Links) nur noch
    mittels AJAX geladen. Das kann auch (z.B. mittels Timer getriggert) sekündlich passieren.
    Das hat dann auf diese Seite und das Input-Feld keinen Einfluss mehr.
</p>

<div>
    <div class="form-row align-items-center">
        <div class="col-sm-3 my-1">
            <input id="filtervalue" type="text" class="form-control" placeholder="Suche...">
        </div>
        <div class="col-auto my-1">
            <button class="btn btn-primary" onclick="loadExams('@ViewData["CurrentSort"]', '1', event)">Los</button>
        </div>
    </div>
</div>

<div id="pvExams">
    <partial name="_ExamList" model="Model" />
</div>

@section scripts {

    <script type="text/javascript">

        function loadExams(sortOrder, pageIndex, e) {
            console.log($("#filtervalue").val());
            if (e) {
                e.preventDefault();
            }

            var url = '@Url.Action("IndexPartial", "Exam")';

            $.ajax({
                type: 'GET',
                contentType: 'application/json; charset=utf-8',
                url: url,
                dataType: 'html',
                data: {
                    "filter": $("#filtervalue").val(),
                    "sortOrder": sortOrder,
                    "pageIndex": pageIndex
                },
                success: function (result) {
                    $('#pvExams').html('');
                    $('#pvExams').html(result);
                },
                error: function (success, message) {
                    alert(message);
                    //window.location = './../Error' //https://localhost:5001/Error
                }
            });
        }

    </script>

}

Spg.TestAdministrator/Spg.TestAdministrator/src/Spg.TestAdministrator.WebApp/Views/Exam/Edit.cshtml
@model Test

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Test</h4>
<hr />

<div class="row">
    <div class="col-md-4">

        <p>
            <span class="alert-danger">@TempData["Error"]</span>
        </p>

        <form asp-action="Edit">
            <div asp-validation-summary="All" class="text-danger"></div>
            <input type="hidden" asp-for="TE_ID" />
            <input type="hidden" asp-for="Guid" />

            <div class="form-group">
                <label asp-for="TE_Class" class="control-label"></label>
                <select asp-for="TE_Class" class="form-control" asp-items="ViewBag.TE_Class"></select>
                <span asp-validation-for="TE_Class" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="TE_Teacher" class="control-label"></label>
                <select asp-for="TE_Teacher" class="form-control" asp-items="ViewBag.TE_Teacher"></select>
                <span asp-validation-for="TE_Teacher" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="TE_Subject" class="control-label"></label>
                <input asp-for="TE_Subject" class="form-control" />
                <span asp-validation-for="TE_Subject" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="TE_Date" class="control-label"></label>
                <input asp-for="TE_Date" class="form-control" />
                <span asp-validation-for="TE_Date" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TE_Lesson" class="control-label"></label>
                <select asp-for="TE_Lesson" class="form-control" asp-items="ViewBag.TE_Lesson"></select>
                <span asp-validation-for="TE_Lesson" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>

    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Spg.TestAdministrator/Spg.TestAdministrator/src/Spg.TestAdministrator.WebApp/Views/Exam/Index.cshtml
@inject Spg.TestAdministrator.Business.Domain.Interfaces.IAuthService _httpCookieAuthService
@model PagenatedList<Test>

@{ 
    var prevDisabled = !Model.HasPreviousPage ? "disabled" : "";
    var nextDisabled = !Model.HasNextPage ? "disabled" : "";
}

<h3>Admin-Dashboard für die Tests</h3>

<form method="get">
    <div class="form-row align-items-center">
        <div class="col-sm-3 my-1">
            <input type="text" class="form-control" name="filter" value="@ViewData["CurrentFilter"]" placeholder="Suche...">
        </div>
        <div class="col-auto my-1">
            <button type="submit" class="btn btn-primary">Los</button>
        </div>
    </div>
</form>

<a asp-action="Index" 
   asp-route-pageIndex="@(Model.PageIndex - 1)"
   asp-route-currentFilter="@ViewData["CurrentFilter"]"
   asp-route-sortOrder="@ViewData["CurrentSort"]"
   class="btn btn-secondary @prevDisabled">
    Previous
</a>
<a asp-action="Index" 
   asp-route-pageIndex="@(Model.PageIndex + 1)"
   asp-route-currentFilter="@ViewData["CurrentFilter"]"
   asp-route-sortOrder="@ViewData["CurrentSort"]"
   class="btn btn-secondary @nextDisabled">
    Next
</a>
<label>(Seite @Model.PageIndex von @Model.TotalPages)</label>

<div class="my-3" />

<p>
    DropDown:
    <form method="post">
        <select value="paraneter01" class="form-control" asp-items="ViewBag.TE_Class"></select>
        <button type="submit" class="btn btn-primary">Los</button>
    </form>
</p>

<table class="table table-striped">
    <thead>
        <tr>
            <td>
                <a asp-action="Index" asp-route-pageIndex="@Model.PageIndex" asp-route-sortOrder="@ViewData["IdSortParm"]" asp-route-currentFilter="@ViewData["CurrentFilter"]">ID</a>
            </td>
            <td>
                <a asp-action="Index" asp-route-pageIndex="@Model.PageIndex" asp-route-sortOrder="@ViewData["DateSortParm"]" asp-route-currentFilter="@ViewData["CurrentFilter"]">Datum</a>
            </td>
            <td>
                <a asp-action="Index" asp-route-pageIndex="@Model.PageIndex" asp-route-sortOrder="@ViewData["SubjectSortParm"]" asp-route-currentFilter="@ViewData["CurrentFilter"]">Fach</a>
            </td>
            <td>Prüfer</td>
            <td></td>
        </tr>
    </thead>
    <tbody>
        @foreach (Test item in Model)
        {
            <tr>
                <td>@item.TE_ID</td>
                <td>@item.TE_Date</td>
                <td>@item.TE_Subject</td>
                <td>@item.TE_TeacherNavigation.T_Firstname @item.TE_TeacherNavigation.T_Lastname</td>
                @if (_httpCookieAuthService.IsAuthenticated
                && _httpCookieAuthService.HasRole("Teacher"))
                {
                    <td><a asp-action="Edit" asp-route-id="@item.Guid">Edit</a></td>
                }
            </tr>
        }
    </tbody>
</table>

Spg.TestAdministrator/Spg.TestAdministrator/src/Spg.TestAdministrator.WebApp/Views/Exam/VueIndex.cshtml
@section Headers
{
    <script src="//unpkg.com/vue@latest/dist/vue.min.js"></script>
    <script src="//unpkg.com/bootstrap-vue@latest/dist/bootstrap-vue.min.js"></script>
}

<div id="app">
    {{ message }}

    <div>
        <div class="form-row align-items-center">
            <div class="col-sm-3 my-1">
                <input type="text" class="form-control" v-model="filter" placeholder="Suche...">
            </div>
            <div class="col-auto my-1">
                <b-button v-on:click="newFilter">Los</b-button>
            </div>
        </div>
    </div>

    <b-button v-on:click="previousPage" variant="outline-primary">Previous</b-button>
    <b-button v-on:click="nextPage" variant="outline-primary">Next</b-button>
    
    <p>
        Seite {{ pageIndex }} von {{ totalPages }}
    </p>

    <table class="table table-striped">
        <thead>
            <tr>
                <th>
                    <a v-on:click="sort('id')">ID</a>
                </th>
                <th>
                    <a v-on:click="sort('date')">Datum</a>
                </th>
                <th>
                    <a v-on:click="sort('subject')">Fach</a>
                </th>
                <th>Prüfer</th>
            </tr>
        </thead>
        <tbody>
            <tr v-for="t in examListDto.exams">
                <td>{{ t.tE_ID }}</td>
                <td>{{ t.tE_Date }}</td>
                <td>{{ t.tE_Subject }}</td>
                <td>{{ t.tE_TeacherNavigation.t_Firstname }} {{ t.tE_TeacherNavigation.t_Lastname }}</td>
            </tr>
        </tbody>
    </table>
</div>

@section Scripts
{

    <script type="text/javascript">

        var app = new Vue({
            el: '#app',
            data: {
                message: '',
                examListDto: null,
                filter: '',
                sortOrder: '',
                sortField: '',
                pageIndex: 1,
                totalPages: 1
            },
            mounted: function () {
                this.pageIndex = 1;
                this.lodadata();
            },
            methods: {
                lodadata: async function () {
                    console.log('loaddata begonnen');
                    this.message = 'Daten werden geladen...';
                    const response = await fetch('/Exam/VueTableContent?'
                        + 'filter=' + this.filter
                        + '&sortField=' + this.sortField
                        + '&pageIndex=' + this.pageIndex, {
                        method: 'GET'
                    });
                    if (response.ok) {
                        this.examListDto = await response.json();
                        console.log(this.examListDto.exams);

                        this.totalPages = this.examListDto.totalPages;
                        console.log(this.totalPages);

                        this.message = 'Alles OK';
                    }
                    else {
                        this.message = 'Es ist ein Fehler aufgetreten!';
                    }
                },
                previousPage: function () {
                    if (this.pageIndex > 1) {
                        this.pageIndex--;
                        this.lodadata();
                    }
                },
                nextPage: function () {
                    if (this.pageIndex < this.totalPages) {
                        this.pageIndex++;
                        this.lodadata();
                    }
                },
                newFilter: function () {
                    this.pageIndex = 1;
                    this.lodadata();
                },
                sort: function (colName) {
                    if (this.sortOrder == '') {
                        this.sortOrder = '_desc';
                    }
                    else {
                        this.sortOrder = '';
                    }
                    this.sortField = colName + this.sortOrder;
                    this.lodadata();
                }
            },
            calculated: {
            }
        });

    </script>

}

Spg.TestAdministrator/Spg.TestAdministrator/src/Spg.TestAdministrator.WebApp/Views/Exam/_ExamList.cshtml
@model PagenatedList<Test>

@{
    var prevDisabled = !Model.HasPreviousPage ? "disabled" : "";
    var nextDisabled = !Model.HasNextPage ? "disabled" : "";
}

<a onclick="loadExams('@ViewData["CurrentSort"]', '@(Model.PageIndex - 1)', event)"
   class="btn btn-secondary @prevDisabled">
    Previous
</a>
<a onclick="loadExams('@ViewData["CurrentSort"]', '@(Model.PageIndex + 1)', event)"
   class="btn btn-secondary @nextDisabled">
    Next
</a>
<label>(Seite @Model.PageIndex von @Model.TotalPages)</label>

<div class="my-3" />

<table class="table table-striped">
    <thead>
        <tr>
            <th>
                <a href="#" onclick="loadExams('@ViewData["IdSortParm"]', '@(Model.PageIndex)', event)">ID</a>
            </th>
            <th>
                <a href="#" onclick="loadExams('@ViewData["DateSortParm"]', '@(Model.PageIndex)', event)">Datum</a>
            </th>
            <th>
                <a href="#" onclick="loadExams('@ViewData["SubjectSortParm"]', '@(Model.PageIndex)', event)">Fach</a>
            </th>
            <th>Prüfer</th>
        </tr>
    </thead>
    <tbody>
        @foreach (Test item in Model)
        {
        <tr>
            <td>@item.TE_ID</td>
            <td>@item.TE_Date</td>
            <td>@item.TE_Subject</td>
            <td>@item.TE_TeacherNavigation.T_Firstname @item.TE_TeacherNavigation.T_Lastname</td>
        </tr>
        }
    </tbody>
</table>